<!-- application/views/scripts/palavrasChaves/insert.phtml -->
 <section class="section_home" >
		<section class="section_home_article" id="article_coluna1" style="" >
			<hgroup>
				<header class="section_header_" style="position:relative; float:none; margin-left:auto; margin-right:auto; display:block; -webkit-box-shadow:rgba(0, 0, 0, 0.289063) 0px 1px 3px; box-shadow:rgba(0, 0, 0, 0.292969) 0px 1px 3px; -o-box-shadow:rgba(0, 0, 0, 0.289063) 0px 1px 3px; -ms-box-shadow:rgba(0, 0, 0, 0.289063) 0px 1px 3px; -moz-box-shadow:rgba(0, 0, 0, 0.289063) 0px 1px 3px; border-top:1px solid rgba(0,183,254,0.50); border-bottom:1px solid rgba(127,127,127,0.10); " ><div id="titulo_text" style="position:relative; width:auto; height:auto; background-color:rgba(0,0,0,0.00); " >Login</div></header>

					<nav id="nav_lorem" style="left:0; top:-1px; " >

					<header style="font-family:unb_officeregular; font-size:13pt; margin-left:60px; margin-top:5px; color:#FFFFFF; " >Entre com seu usuário e senha</header></nav>
						<article class="form_article_global" >
							<?php
							$this->form->setAction($this->url());
							echo $this->form;
							?>
							<div style="clear:both; " ></div></ul>
								
							</section>
						</dl>
							<div style="clear:both; " ></div>
				</form>
				<div style="clear:both; " ></div>
			</article>
		</hgroup>
</section>
		
				
