<!-- application/views/scripts/palavrasChaves/insert.phtml -->
 <section class="section_home" >
		<section class="section_home_article" id="article_coluna1" style="" >
			<hgroup>
				<header class="section_header_" style="position:relative; float:none; margin-left:auto; margin-right:auto; display:block; -webkit-box-shadow:rgba(0, 0, 0, 0.289063) 0px 1px 3px; box-shadow:rgba(0, 0, 0, 0.292969) 0px 1px 3px; -o-box-shadow:rgba(0, 0, 0, 0.289063) 0px 1px 3px; -ms-box-shadow:rgba(0, 0, 0, 0.289063) 0px 1px 3px; -moz-box-shadow:rgba(0, 0, 0, 0.289063) 0px 1px 3px; border-top:1px solid rgba(0,183,254,0.50); border-bottom:1px solid rgba(127,127,127,0.10); " ><div id="titulo_text" style="position:relative; width:auto; height:auto; background-color:rgba(0,0,0,0.00); " >Ambiente de administração</div></header>

					<nav id="nav_lorem" style="left:0; top:-1px; " >

					<header style="font-family:unb_officeregular; font-size:13pt; margin-left:60px; margin-top:5px; color:#FFFFFF; " >Escolha uma das ações abaixo</header></nav>
						<article class="form_article_global" >
							<h4>Edição e exclusão:</h4>
							<p><a href="solucoes/indexadmin">Solução</a></p>
                            <p><a href="servicos/indexadmin">Serviços</a></p>

							<h4>Formulários de Inserção:</h4>
							<p><a href="solucoes/insert">Solução</a></p>
							<p><a href="servicos/insert">Serviços</a></p>

							<h4>Formulários Ligados ao Formulário de Solução:</h4>
							<p><a href="depositos/insert">Depósitos</a></p>
							<p><a href="titular/insert">Titular</a></p>
							<p><a href="modalidade-protecao/insert">Modalidade de Proteção</a></p>
							<p><a href="classificacoes/insert">Classificações</a></p>
							<div style="clear:both; " ></div></ul>
								
							</section>
						</dl>
							<div style="clear:both; " ></div>
				</form>
				<div style="clear:both; " ></div>
			</article>
		</hgroup>
</section>
		
				
