<!--Começo do Footer-->
<footer id="footer" >
    <section id="section_footer" >
        <figure class="footer_figure" style="float:left; background-image:url(imagem/logo_cdt.png);" ></figure>
        <figure class="footer_figure" style="float:right; background-image:url(imagem/logo_unb.png);" ></figure>
        <section style="float:left; text-align:right; padding-top:5px; " >
            Universidade de Brasília - Edifício CDT <br>
            Campus Universitário Darcy Ribeiro <br>
            Brasília - Distrito Federal <br>
            Caixa Postal: 04397 Cep: 70904-970 <br>
        </section>
        <section style="float:right; text-align:left; padding-top:5px; margin-right:30px; " >
            E-mail: atendimento@cdt.unb.br <br>
            Telefone: + 55 61 3107-4100 <br>
            Fax: + 55 61 3107-4136 <br>
        </section>
        <div style="clear:both; " ></div>
    </section>
    <div style="clear:both; " ></div>
</footer>
