<!-- 20120921 -->
<div class="central">	
	<a href="index"><div class="logo"></div></a>
	<div class="menu">
		<ul class="menuTopo">
			<li><a href="index">In&iacute;cio</a></li>
			<li><a href="solucoes">Solu&ccedil;&otilde;es</a></li>
			<li><a href="servicos">Servi&ccedil;os</a></li>
			<li><a href="noticias">Not&iacute;cias</a></li>
			<li><a href="contato">Contato</a></li>
		</ul>
	</div>
		<section class="section_busca" >			
			<form method="post" action="busca" style="width:auto; height:auto; " >
				<input class="form_busca" id="busca" type="text" name="busca" placeholder="Pesquisar" value="<?php echo $this->busca;?>" />
				<input type="submit" value="Ir" class="form_busca_botao" />
			<div style="clear:both; " ></div>
		</form>
			<div style="clear:both; " ></div>
		</section>	
</div>	
