<!-- application/layouts/scripts/layout.phtml -->
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
		<meta name="author" content="ACT" >
		<meta name="description" content="ACT" >
		<meta name="keywords" content="ACT" >
		<title>ACT | Beta v0.5.1</title>
		<link href="/css/global.css" rel="stylesheet" media="screen" type="text/css" >
		<link href="/css/main.css" rel="stylesheet" media="screen" type="text/css" >
		<link rel="shortcut icon" href="imagem/favicon.ico" />
		<script type="text/javascript" src="/js/libs/jquery-1.6.2.min.js" ></script>
		<script type="text/javascript" src="/js/basic-jquery-slider.js" ></script>
		<link href="/css/basic-jquery-slider.css" rel="stylesheet" media="screen" type="text/css" >
		<link href="/fonts/font.css" rel="stylesheet" media="screen" type="text/css" >
	</head>
<body class="body_main_content" >	
		<?php echo $this->layout()->content ?>
</body></html>
