<style>
    footer{
        margin-top: -230px;
    }
</style>
<section class="section_home" >
    <section class="section_home_article" id="article_coluna1" style="" >
        <hgroup>
            <header class="section_header_" id="section_header_contato" >
                <div id="titulo_text" style="position:relative; width:auto; height:auto; background-color:rgba(0,0,0,0.00); " >Contato</div></header>
            <nav id="nav_lorem" style="left:0; top:-1px; " >
                <header id="subtitle_contato" >Entre em contato que esclareceremos suas dúvidas</header>
            </nav>
        </hgroup>
        <article class="article_contato" id="texto_artigo" style="padding-right:5px; padding-left:5px; padding-top:50px; " >
        <?php
        $this->form->setAction($this->url());
        echo $this->form;
        ?>
        <section class="section_contato_institucional" >
            <section>
                <figure class="contato_fig" style="background-image:url(imagem/logo_act.png); " ></figure>
                <aside style="margin-top:20px; width:auto; float:left; " >
                    Universidade de Brasília - Edifício CDT <br>
                    Campus Universitário Darcy Ribeiro <br>
                    Brasília - Distrito Federal <br>
                    Caixa Postal: 04397 Cep: 70904-970<br>
                    E-mail: act@cdt.unb.br <br>
                    Telefone: + 55 61 3107-4116 <br>
                </aside>
            </section>

            <div class="line_divide_sections" ></div>

            <section>
                <figure class="contato_fig" style="background-image:url(imagem/logo_disque.png); " ></figure>
                <aside style="width:auto; float:left; " >
                    Universidade de Brasília - Edifício CDT <br>
                    Campus Universitário Darcy Ribeiro <br>
                    Brasília - Distrito Federal <br>
                    Caixa Postal: 04397 Cep: 70904-970<br>
                    E-mail: disque@cdt.unb.br <br>
                    Telefone: + 55 61 3107-4116/4147 <br>
                </aside>
            </section>
        </section>

    </article>
    </section>
</section>
    <div style="clear:both;"></div>
<!--Fim do Fórumlário-->